WIP: Logger/verbosity implemented.
Enroutemx/pyroute pull request #30
Opened 2018-02-27 17:31 UTC by armando-montalvo

The verbosity decorator class was implemented. This gives us the flexibility to choose a verbosity level in the json file. It is a work in progress to implement the verbosity level in the command line, and to define which functions fall under which verbosity level.

The config.json file must be modified like in the next link: https://irock.enroute.xyz/wiki/index.php/Pyroute_Installation#Configuration

2018-03-03 15:08 UTC, atrevino commented
Can you rebase and just send your commit?

2018-03-03 15:09 UTC, atrevino89 requested changes
Can you move out my commit about the license and send only your commit?

2018-03-07 23:15 UTC, elohimf commented
@armando-montalvo remove 6387acc from the commit list to approve this.

2018-03-14 16:48 UTC, armando-montalvo commented
Ready, credits to @eisaaclrubio !

2018-03-15 06:46 UTC, merged