A small Sphinx comments
Enroutemx/pyroute pull request #34
Opened 2018-03-05 22:00 UTC by vahev

This PR adds just a little of Sphinx-ready comments for utils module

2018-03-07 23:22 UTC, elohimf requested changes
The comments are missing the argument explanations and types. For example, clean_filenames takes a single arg, filenames, which is a list of strings. Consider using :param, :type and :returns for this.

2018-03-08 18:50 UTC, vahev commented
@elohimf check it out, I've already done the changes that you mentioned before.

2018-03-09 03:13 UTC, elohimf requested changes
Also, you should use interactive rebase to squash your commits into one, to keep everything tidy.

2018-03-09 03:13 UTC, elohimf commented on pyroute/utils.py
> +        :returns List: A list of dunder methods
I think you mean "A list of non-dunder methods" here, as this method deletes all dunder methods.

2018-03-09 16:08 UTC, vahev commented
@elohimf I've already put my last commits into a single one. Also made the small change to utils file.

2018-03-12 20:41 UTC, elohimf approved these changes

2018-03-12 20:42 UTC, merged