8
Enroutemx/pyroute pull request #35
Opened 2018-03-13 19:20 UTC by marioBZ7

Documentation added to run.py with Sphinx format.
Waiting for approval.

2018-03-15 06:54 UTC, elohimf commented
Remember to rebase before making a PR and after other PRs have been approved. There seems to be a lot of commits that have been merged already. Also, besides the milestone code, there should be a descriptive name (or description, repetitions aside) on the title of this PR.

2018-03-16 02:14 UTC, atrevino89 requested changes
Can you please send only your code, do a fetch & rebase then a forced push to your repo.

2018-03-16 08:09 UTC, marioBZ7 commented
Sorry guys, I was trying to merge into master. I already changed this PR to develop and now it's just 1 commit, the actual commit I'm trying to merge.

2018-03-22 15:30 UTC, eisaaclrubio reviewed
@marioBZ7 When the documentation is generated the blank lines will force the comment to jump to the next line, please remove them so the documentation is written nicely.

2018-03-22 15:30 UTC, eisaaclrubio commented on pyroute/run.py
> +
@marioBZ7 can you remove the blank space between each line, from line 4 to line 7?

2018-03-22 15:30 UTC, eisaaclrubio commented on pyroute/run.py
> +   """
@marioBZ7 same here, please remove the line 36

2018-03-22 15:30 UTC, eisaaclrubio commented on pyroute/run.py
> +        """
@marioBZ7 same here with the lines 55 and 61.

2023-12-03 22:19 UTC, closed without merging

2023-12-03 22:19 UTC, marioabz commented
??????